In [1]:
import pandas as pd

In [2]:
file = pd.read_csv('./Acc_20250422_0830.csv')

In [8]:
pd.set_option('display.max_columns', None)

In [16]:
file.groupby('OverdueCnt').size()

OverdueCnt
0:GRACE              45
1:XD              20824
2:OD1             10566
3:OD2              9224
4:OD3              8473
5:OD4              7920
6:OD5              8227
7:OD6              5937
98:Write-Off     117879
99:NORMAL       1263624
dtype: int64

In [23]:
file.head()

,BaseDate,Loan No,Product Code,Overdue Start Date,OverdueDays_Morning,OverdueCnt_Morning,OverdueDays,OverdueCnt,Loan Amt,Loan Balance,Outstanding Balance,OverdueSumAmt,OverduePrin,OverdueInt,OverdueCrUsage,OverdueOutputTax,OverdueCollectionFee,OverdueVAT,OverdueStampTaxAmt,OverdueNCBTaxAmt,OverdueETCFeeAmt,LawCost,LastPaymentDt,LastPaymentAmt
0,20250422,9010221122000949,A501:TL,2024-11-01,172,6:OD5,172,6:OD5,74164.44,33528.80,36289.88,16750.0,13759.8,1697.83,792.37,0.0,467.3,32.7,0,0,0.0,0.0,2025-03-31,3067.00
1,20250422,9010221122000931,A501:TL,,0,99:NORMAL,0,99:NORMAL,41659.76,11088.74,11240.68,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0,0,0.0,0.0,2024-09-27,20971.92
2,20250422,9010221122000922,A501:TL,2023-08-31,0,98:Write-Off,0,98:Write-Off,34238.99,23851.00,27185.38,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0,0,0.0,0.0,2023-01-31,1300.00
3,20250422,9010221122000914,A501:TL,2024-02-29,0,98:Write-Off,0,98:Write-Off,16118.33,13559.55,15534.96,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0,0,0.0,0.0,2023-12-27,550.00
4,20250422,9010221122000906,A501:TL,2022-11-30,0,98:Write-Off,0,98:Write-Off,35235.40,31005.17,34727.73,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0,0,0.0,0.0,2022-09-30,2100.00

In [29]:
file = file.loc[file['OverdueSumAmt'] != 0]

In [30]:
file

,BaseDate,Loan No,Product Code,Overdue Start Date,OverdueDays_Morning,OverdueCnt_Morning,OverdueDays,OverdueCnt,Loan Amt,Loan Balance,Outstanding Balance,OverdueSumAmt,OverduePrin,OverdueInt,OverdueCrUsage,OverdueOutputTax,OverdueCollectionFee,OverdueVAT,OverdueStampTaxAmt,OverdueNCBTaxAmt,OverdueETCFeeAmt,LawCost,LastPaymentDt,LastPaymentAmt
0,20250422,9010221122000949,A501:TL,2024-11-01,172,6:OD5,172,6:OD5,74164.44,33528.80,36289.88,16750.0,13759.80,1697.83,792.37,0.0,467.30,32.70,0,0,0.0,0.0,2025-03-31,3067.0
34,20250422,9010221122000566,A501:TL,2025-04-01,21,1:XD,21,1:XD,22467.25,6000.84,6255.93,708.0,600.47,73.31,34.22,0.0,0.00,0.00,0,0,0.0,0.0,2025-03-26,708.0
40,20250422,9010221122000507,A501:TL,2025-04-01,21,1:XD,21,1:XD,86911.79,52878.37,55024.04,2177.0,1267.32,617.00,242.68,0.0,46.73,3.27,0,0,0.0,0.0,2025-03-25,2177.0
62,20250422,9010221122000221,A501:TL,2025-02-01,80,3:OD2,80,3:OD2,98044.61,52499.85,55451.97,6144.0,4200.15,1251.57,492.28,0.0,186.92,13.08,0,0,0.0,0.0,2025-04-05,1000.0
67,20250422,9010221122000175,A501:TL,2025-01-01,111,4:OD3,111,4:OD3,64671.95,34224.76,36924.16,6954.0,4696.55,1481.23,476.22,0.0,280.38,19.62,0,0,0.0,0.0,2025-04-01,1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452714,20250422,1000158090014831,A401:ML,2017-02-01,0,99:NORMAL,0,99:NORMAL,25500.00,100.00,100.00,100.0,100.00,0.00,0.00,0.0,0.00,0.00,0,0,0.0,0.0,2017-01-31,1580.0
1452715,20250422,1000158090014814,A401:ML,2017-08-01,0,99:NORMAL,0,99:NORMAL,24600.00,30.00,30.00,30.0,30.00,0.00,0.00,0.0,0.00,0.00,0,0,0.0,0.0,2017-07-31,1260.0
1452716,20250422,1000158090008580,A401:ML,2017-08-01,0,99:NORMAL,0,99:NORMAL,25900.00,100.00,100.00,100.0,100.00,0.00,0.00,0.0,0.00,0.00,0,0,0.0,0.0,2017-07-16,4000.0
1452717,20250422,1000158090005394,A401:ML,2017-08-01,0,99:NORMAL,0,99:NORMAL,25900.00,100.00,100.00,100.0,100.00,0.00,0.00,0.0,0.00,0.00,0,0,0.0,0.0,2017-08-01,2600.0
1452718,20250422,1000158080014811,A401:ML,2017-02-01,0,99:NORMAL,0,99:NORMAL,27900.00,100.00,100.00,100.0,100.00,0.00,0.00,0.0,0.00,0.00,0,0,0.0,0.0,2017-02-03,3200.0

In [28]:
file.loc[file['Loan No'] == 7240970103909468]

,BaseDate,Loan No,Product Code,Overdue Start Date,OverdueDays_Morning,OverdueCnt_Morning,OverdueDays,OverdueCnt,Loan Amt,Loan Balance,Outstanding Balance,OverdueSumAmt,OverduePrin,OverdueInt,OverdueCrUsage,OverdueOutputTax,OverdueCollectionFee,OverdueVAT,OverdueStampTaxAmt,OverdueNCBTaxAmt,OverdueETCFeeAmt,LawCost,LastPaymentDt,LastPaymentAmt
496518,20250422,7240970103909468,A701:SF,,0,99:NORMAL,0,99:NORMAL,5520.89,2760.41,2760.41,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2025-04-06,460.08

In [6]:
file.columns

Index(['BaseDate', 'Loan No', 'Product Code', 'Overdue Start Date',
       'OverdueDays_Morning', 'OverdueCnt_Morning', 'OverdueDays',
       'OverdueCnt', 'Loan Amt', 'Loan Balance', 'Outstanding Balance',
       'OverdueSumAmt', 'OverduePrin', 'OverdueInt', 'OverdueCrUsage',
       'OverdueOutputTax', 'OverdueCollectionFee', 'OverdueVAT',
       'OverdueStampTaxAmt', 'OverdueNCBTaxAmt', 'OverdueETCFeeAmt', 'LawCost',
       'LastPaymentDt', 'LastPaymentAmt'],
      dtype='object')