In [1]:
import pandas as pd
# from utils import all_history, transform_files
import glob
import numpy as np
import pandas as pd
import glob
# import win32com.client as win32
import jaydebeapi
# from const import QUERY, CONNECT
import re

In [2]:
assign = pd.read_excel(f"./input/3.Total assign Mar'25 (1).xlsx")

In [3]:
assign.columns

Index(['Base date', 'Customer No', 'Customer ID No', 'Principal balance',
       'Total Unclaimed Amt.', 'Repayment Target Amount',
       'Overdue days(Morning)', 'Overdue Cnt(Morning)', 'Overdue days',
       'Num of Overdue months', 'Overdue Months Division Code', 'Corp. Info.',
       'Sales product code', 'Loan No.', 'Customer Name', 'Customer ID No.',
       'Mobile No.', 'Address(Home)', 'Post code', 'Phone No.(Home)',
       'Address(Office)', 'Post code.1', 'Biz phone No.',
       'Address (place of residence)', 'Post Code', 'Phone No.',
       'Delivery Address', 'Post code.2', 'Delivery phone No.',
       'Customer relationship', 'Related person', 'Phone No. 1',
       'Customer relationship.1', 'Related person.1', 'Phone No. 2',
       'Branch code', 'Outstanding Balance', 'Loan date', 'Installment Count',
       'Product Name', 'Last Money Received date', 'Last payment Amt.',
       'Loan Amt.', 'Principal', 'Monthly payment Amt.',
       ' First_Settlement_date', 'Last payment date', 'Billing interest Amt.',
       'Billing Credit Usage Amount', 'Overdue start date', 'Overdue Int.',
       'Overdue Credit Usage Amount', 'Collection Fee', 'Overdue Sum. Amt.',
       'Overdue Months Division Code.1', 'DOB', 'Marital status',
       'Phone No. 3', 'Company name', 'Company Extension No.',
       'Headquarter Phone No', 'Headquarter Extension No.', 'Monthly income',
       'Email Address', 'Next payment due date', 'Next Payment Amt',
       'Payment date', 'Total count', 'Number of deposit on 1st of month',
       'Number of deposit on/Before 5th of month',
       'Number of deposit before 24th of month',
       'Number of deposit before 25th of month',
       'Number of deposit at the end of month.', 'Last payment Amt..1',
       'Biz. industry code', 'Occupation', 'Sales product code.1',
       'Waived Processing Amt.(Xday)', 'Extend term changed count', 'Ever',
       'Product', 'Status LM', 'Old OA', 'New OA', 'Reason', 'Collector'],
      dtype='object')

In [4]:
assign

,Base date,Customer No,Customer ID No,Principal balance,Total Unclaimed Amt.,Repayment Target Amount,Overdue days(Morning),Overdue Cnt(Morning),Overdue days,Num of Overdue months,...,Sales product code.1,Waived Processing Amt.(Xday),Extend term changed count,Ever,Product,Status LM,Old OA,New OA,Reason,Collector
0,02-03-2568,14220046109,3240900116555,23541.73,0.0,706.25,1,1,1,1,...,A301:RL,0,0,N,RL ML TL,SAVE,KOR,KOR,2025-03-05,NaN
1,02-03-2568,14220082584,3100700619422,82466.01,0.0,2473.98,1,1,1,1,...,A301:RL,0,0,N,RL ML TL,NEW,NaN,Delay calling,NaT,NaN
2,02-03-2568,14230283551,3101300732206,424.47,0.0,432.40,1,1,1,1,...,A401:ML,0,0,N,RL ML TL,SAVE,Delay calling,Delay calling,NaT,NaN
3,02-03-2568,14230554514,3321200109131,33990.39,0.0,2638.96,60,3,60,3,...,A301:RL,0,0,N,RL ML TL,UNSAVE,PCN,KOR,NaT,NaN
4,02-03-2568,14220054168,3100503160974,10233.80,0.0,1405.00,1,1,1,1,...,A401:ML,0,0,N,RL ML TL,NEW,NaN,Delay calling,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40416,02-03-2568,12170054073,3450500230537,16060.20,NaN,2210.00,182,7,182,7,...,A501:TL,0,0,Y,TDR,UNSAVE,KWC,KWC,2025-03-06,NaN
40417,02-03-2568,12170041231,1910400006979,14160.31,NaN,3270.00,182,7,182,7,...,A501:TL,0,0,Y,TDR,UNSAVE,GMV,MMN,2025-03-06,NaN
40418,02-03-2568,12170013450,1260300010989,14121.51,NaN,3158.00,182,7,182,7,...,A501:TL,0,0,Y,TDR,UNSAVE,KWC,KWC,2025-03-06,NaN
40419,02-03-2568,14220152007,5401300004930,13742.00,NaN,1775.00,182,7,182,7,...,A501:TL,0,0,Y,TDR,UNSAVE,MMN,KWC,2025-03-06,NaN
40420,02-03-2568,14220037485,1309801416420,11594.48,NaN,1451.00,182,7,182,7,...,A501:TL,0,0,Y,TDR,UNSAVE,MGC,KWC,2025-03-06,NaN

In [5]:
assign = assign.loc[
    (assign['New OA'] == 'Delay calling')
][['Base date','Customer ID No','Principal balance','Customer Name', 'Sales product code','Mobile No.'
        ,'Overdue Months Division Code','Customer No','Overdue days(Morning)','Status LM','New OA' ]]

In [6]:
assign

,Base date,Customer ID No,Principal balance,Customer Name,Sales product code,Mobile No.,Overdue Months Division Code,Customer No,Overdue days(Morning),Status LM,New OA
1,02-03-2568,3100700619422,82466.01,วัชรพล ชัยสวัสดิ์,A301:RL,859110632.0,Grace_X-Day,14220082584,1,NEW,Delay calling
2,02-03-2568,3101300732206,424.47,ธนะโชติ ตันทิวากร,A401:ML,870876086.0,Grace_X-Day,14230283551,1,SAVE,Delay calling
4,02-03-2568,3100503160974,10233.80,ชัยวัฒน์ สวนแก้ว,A401:ML,837760058.0,Grace_X-Day,14220054168,1,NEW,Delay calling
5,02-03-2568,1459900793051,2590.98,จันทรกานต์ ปรินแคน,A401:ML,983074011.0,Grace_X-Day,14230406466,1,NEW,Delay calling
7,02-03-2568,3101701963284,18242.39,สุทิน หวังบู่,A301:RL,843095398.0,Grace_X-Day,14230951043,1,SAVE,Delay calling
...,...,...,...,...,...,...,...,...,...,...,...
38104,02-03-2568,3489900074743,263412.48,ณัฐนันท์ สิทธิธรรมพงศ์,A301:RL,865649741.0,Grace_X-Day,12180048102,1,NEW,Delay calling
38105,02-03-2568,3610500062721,62662.70,อนงค์ ขุมเพ็ชร,A301:RL,817357962.0,Grace_X-Day,12160031301,1,SAVE,Delay calling
38109,02-03-2568,3800900578278,20232.96,ภิรมย์ จริตงาม,A301:RL,902252226.0,Grace_X-Day,12170059023,1,SAVE,Delay calling
38110,02-03-2568,3820800162096,46587.05,นิตยา ชาติมณตรี,A301:RL,878841915.0,Grace_X-Day,12160033410,1,SAVE,Delay calling
38112,02-03-2568,1100400134435,58220.40,วลีวรรณ เรืองราย,A301:RL,808692914.0,Grace_X-Day,12200000014,1,NEW,Delay calling